package config

import "github.com/abdo-355/llm-gateway/internal/types"

// Weights are coarse routing priors, not precise rankings. Bands:
//
//	0.94–0.98 exceptional/near-king   0.86–0.92 excellent
//	0.78–0.84 strong                  0.68–0.76 competent fallback
//	0.56–0.66 deep fallback           0.40–0.54 untrusted/free-pool emergency
//
// Live health/success/concurrency scoring dynamically adjusts rankings at runtime.
var tierRegistry = map[types.Tier]types.TierConfig{
	types.TierDefault: {
		Tier: types.TierDefault,
		Entries: []types.TierEntry{
			{Provider: "groq", Model: "qwen/qwen3.8-27b", Weight: 0.95},
			{Provider: "groq", Model: "qwen/qwen3.6-27b", Weight: 0.94},
			{Provider: "gemini", Model: "gemini-3.5-flash-lite", Weight: 0.92},
			{Provider: "inferx", Model: "Qwen3.8-27B-FP8", Weight: 0.88},
			{Provider: "opencode", Model: "muse-spark-1.3-contributor-free", Weight: 0.88},
			{Provider: "opencode", Model: "muse-spark-1.2-contributor-free", Weight: 0.86},
			{Provider: "empero", Model: "glm-5.3-flash", Weight: 0.86},
			{Provider: "empero", Model: "deepseek-v4-flash", Weight: 0.86},
			{Provider: "bai", Model: "glm-5.3-flash", Weight: 0.86},
			{Provider: "bai", Model: "qwen3.8-flash", Weight: 0.86},
			{Provider: "gmi", Model: "MiniMaxAI/MiniMax-M3", Weight: 0.86},
			{Provider: "vercel", Model: "minimax/minimax-m3-free", Weight: 0.85},
			{Provider: "inferx", Model: "Qwen3.6-35B-A3B-FP8", Weight: 0.85},
			{Provider: "opencode", Model: "nemotron-3-ultra-free", Weight: 0.84},
			{Provider: "zai", Model: "glm-4.7-flash", Weight: 0.84},
			{Provider: "zai", Model: "glm-4.5-flash", Weight: 0.83},
			{Provider: "cloudflare", Model: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", Weight: 0.83},
			{Provider: "cloudflare", Model: "@cf/qwen/qwen2.5-coder-32b-instruct", Weight: 0.82},
			{Provider: "cloudflare", Model: "@cf/qwen/qwen3.8-27b", Weight: 0.82},
			{Provider: "gemini", Model: "gemma-4-31b-it", Weight: 0.82},
			{Provider: "inferx", Model: "Qwen3-Coder-Next-FP8", Weight: 0.82},
			{Provider: "opencode", Model: "deepseek-v4-flash-free", Weight: 0.81},
			{Provider: "orca", Model: "deepseek/deepseek-v4-flash-free", Weight: 0.81},
			{Provider: "gemini", Model: "gemini-3.1-flash-lite", Weight: 0.80},
			{Provider: "gmi", Model: "MiniMaxAI/MiniMax-M2.7", Weight: 0.80},
			{Provider: "vercel", Model: "minimax/minimax-m2.7-free", Weight: 0.80},
			{Provider: "orca", Model: "qwen/qwen3.8-27b-free", Weight: 0.79},
			{Provider: "gemini", Model: "gemma-4-26b-a4b-it", Weight: 0.78},
			{Provider: "groq", Model: "openai/gpt-oss-120b", Weight: 0.78},
			{Provider: "bai", Model: "mimo-v2.5", Weight: 0.78},
			{Provider: "inferx", Model: "Devstral-2-123B-Instruct-2512-int4-AutoRound", Weight: 0.78},
			{Provider: "kilo", Model: "nvidia/nemotron-3-ultra-550b-a55b:free", Weight: 0.77},
			{Provider: "kilo", Model: "nvidia/nemotron-3-super-120b-a12b:free", Weight: 0.76},
			{Provider: "kilo", Model: "poolside/laguna-s-2.1:free", Weight: 0.76},
			{Provider: "kilo", Model: "thinkingmachines/inkling:free", Weight: 0.76},
			{Provider: "opencode", Model: "mimo-v2.5-free", Weight: 0.76},
			{Provider: "kilo", Model: "google/gemma-4-26b-a4b-it:free", Weight: 0.75},
			{Provider: "kilo", Model: "minimax/minimax-m3-free", Weight: 0.75},
			{Provider: "opencode", Model: "big-pickle", Weight: 0.75},
			{Provider: "orca", Model: "orcarouter/free", Weight: 0.75},
			{Provider: "cohere", Model: "command-r7b-12-2024", Weight: 0.74},
			{Provider: "opencode", Model: "ling-3.0-flash-fin-free", Weight: 0.74},
			{Provider: "kilo", Model: "nvidia/nemotron-3.5-lightning:free", Weight: 0.73},
			{Provider: "cloudflare", Model: "@cf/qwen/qwen3-30b-a3b-fp8", Weight: 0.73},
			{Provider: "cloudflare", Model: "@cf/google/gemma-4-26b-a4b-it", Weight: 0.73},
			{Provider: "cloudflare", Model: "@cf/mistralai/mistral-small-3.1-24b-instruct", Weight: 0.72},
			{Provider: "vercel", Model: "poolside/laguna-s-2.1-free", Weight: 0.72},
			{Provider: "cloudflare", Model: "@cf/meta/llama-4-scout-17b-16e-instruct", Weight: 0.71},
			{Provider: "groq", Model: "openai/gpt-oss-20b", Weight: 0.70},
			{Provider: "bai", Model: "hy3", Weight: 0.70},
			{Provider: "opencode", Model: "nemotron-3.5-lightning-free", Weight: 0.68},
			{Provider: "oci", Model: "meta.llama-3.3-70b-instruct", Weight: 0.68},
			{Provider: "gemini", Model: "gemini-3.8-flash", Weight: 0.67},
			{Provider: "gemini", Model: "gemini-3.7-flash", Weight: 0.66},
			{Provider: "gemini", Model: "gemini-3.6-flash", Weight: 0.65},
			{Provider: "ollama", Model: "gemma4:31b", Weight: 0.65},
			{Provider: "gemini", Model: "gemini-2.5-flash", Weight: 0.64},
			{Provider: "ollama", Model: "gpt-oss:20b", Weight: 0.64},
			{Provider: "gemini", Model: "gemini-3-flash-preview", Weight: 0.63},
			{Provider: "gemini", Model: "gemini-2.5-flash-lite", Weight: 0.62},
			{Provider: "opencode", Model: "laguna-s-2.1-free", Weight: 0.60},
			{Provider: "ollama", Model: "nemotron-3-nano:30b", Weight: 0.60},
			{Provider: "nous", Model: "upstage/solar-pro4:free", Weight: 0.58},
			{Provider: "nous", Model: "stepfun/step-3.7-flash:free", Weight: 0.56},
			{Provider: "nous", Model: "tencent/hy3:free", Weight: 0.54},
			{Provider: "nous", Model: "meituan/longcat-2.0:free", Weight: 0.54},
			{Provider: "nous", Model: "poolside/laguna-s-2.1:free", Weight: 0.52},
			{Provider: "nous", Model: "poolside/laguna-xs-2.1:free", Weight: 0.50},
			{Provider: "openrouter", Model: "nvidia/nemotron-3-super-120b-a12b:free", Weight: 0.48},
			{Provider: "openrouter", Model: "nvidia/nemotron-3-ultra-550b-a55b:free", Weight: 0.47},
			{Provider: "openrouter", Model: "z-ai/glm-5.2:free", Weight: 0.46},
			{Provider: "openrouter", Model: "google/gemma-4-31b-it:free", Weight: 0.45},
			{Provider: "openrouter", Model: "nvidia/nemotron-3.5-lightning:free", Weight: 0.44},
			{Provider: "openrouter", Model: "cohere/north-mini-code:free", Weight: 0.42},
			{Provider: "openrouter", Model: "poolside/laguna-s-2.1:free", Weight: 0.42},
			{Provider: "openrouter", Model: "thinkingmachines/inkling:free", Weight: 0.41},
			{Provider: "openrouter", Model: "google/gemma-4-26b-a4b-it:free", Weight: 0.41},
			{Provider: "openrouter", Model: "dots-studio/dots-3-note-preview:free", Weight: 0.40},
		},
		SLO: &types.TierSLO{
			MaxLatencyMs: intPtr(30000),
		},
	},
	types.TierPro: {
		Tier: types.TierPro,
		Entries: []types.TierEntry{
			{Provider: "gemini", Model: "gemini-3.8-flash", Weight: 0.98},
			{Provider: "gemini", Model: "gemini-3.7-flash", Weight: 0.98},
			{Provider: "opencode", Model: "muse-spark-1.2-contributor-free", Weight: 0.96},
			{Provider: "opencode", Model: "nemotron-3-ultra-free", Weight: 0.94},
			{Provider: "inferx", Model: "Qwen3-Coder-Next-FP8", Weight: 0.93},
			{Provider: "gemini", Model: "gemini-3.6-flash", Weight: 0.92},
			{Provider: "gmi", Model: "MiniMaxAI/MiniMax-M3", Weight: 0.92},
			{Provider: "groq", Model: "qwen/qwen3.8-27b", Weight: 0.91},
			{Provider: "vercel", Model: "minimax/minimax-m3-free", Weight: 0.91},
			{Provider: "inferx", Model: "Devstral-2-123B-Instruct-2512-int4-AutoRound", Weight: 0.91},
			{Provider: "empero", Model: "glm-5.3-flash", Weight: 0.90},
			{Provider: "empero", Model: "deepseek-v4-flash", Weight: 0.90},
			{Provider: "bai", Model: "glm-5.3-flash", Weight: 0.90},
			{Provider: "groq", Model: "qwen/qwen3.6-27b", Weight: 0.90},
			{Provider: "bai", Model: "qwen3.8-flash", Weight: 0.89},
			{Provider: "bai", Model: "mimo-v2.5", Weight: 0.88},
			{Provider: "openrouter", Model: "nvidia/nemotron-3-super-120b-a12b:free", Weight: 0.88},
			{Provider: "zai", Model: "glm-4.7-flash", Weight: 0.88},
			{Provider: "zai", Model: "glm-4.5-flash", Weight: 0.87},
			{Provider: "inferx", Model: "Qwen3.8-27B-FP8", Weight: 0.87},
			{Provider: "cloudflare", Model: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", Weight: 0.86},
			{Provider: "gemini", Model: "gemini-3.5-flash", Weight: 0.86},
			{Provider: "orca", Model: "deepseek/deepseek-v4-flash-free", Weight: 0.86},
			{Provider: "cloudflare", Model: "@cf/qwen/qwen2.5-coder-32b-instruct", Weight: 0.85},
			{Provider: "openrouter", Model: "z-ai/glm-5.2:free", Weight: 0.85},
			{Provider: "vercel", Model: "minimax/minimax-m2.7-free", Weight: 0.84},
			{Provider: "gmi", Model: "MiniMaxAI/MiniMax-M2.7", Weight: 0.84},
			{Provider: "inferx", Model: "Qwen3.6-35B-A3B-FP8", Weight: 0.83},
			{Provider: "orca", Model: "qwen/qwen3.8-27b-free", Weight: 0.82},
			{Provider: "kilo", Model: "nvidia/nemotron-3-ultra-550b-a55b:free", Weight: 0.80},
			{Provider: "ollama", Model: "nemotron-3-ultra", Weight: 0.80},
			{Provider: "kilo", Model: "google/gemma-4-26b-a4b-it:free", Weight: 0.78},
			{Provider: "gemini", Model: "gemma-4-31b-it", Weight: 0.78},
			{Provider: "groq", Model: "openai/gpt-oss-120b", Weight: 0.78},
			{Provider: "bai", Model: "hy3", Weight: 0.78},
			{Provider: "ollama", Model: "gpt-oss:120b", Weight: 0.76},
			{Provider: "cohere", Model: "command-r7b-12-2024", Weight: 0.75},
			{Provider: "ollama", Model: "nemotron-3-super", Weight: 0.72},
			{Provider: "opencode", Model: "laguna-s-2.1-free", Weight: 0.60},
			{Provider: "kilo", Model: "poolside/laguna-s-2.1:free", Weight: 0.56},
		},
		SLO: &types.TierSLO{
			MaxLatencyMs: intPtr(30000),
		},
	},
	types.TierMax: {
		Tier: types.TierMax,
		Entries: []types.TierEntry{
			{Provider: "gemini", Model: "gemini-3.8-flash", Weight: 0.98},
			{Provider: "gemini", Model: "gemini-3.7-flash", Weight: 0.98},
			{Provider: "opencode", Model: "muse-spark-1.3-contributor-free", Weight: 0.98},
			{Provider: "opencode", Model: "muse-spark-1.2-contributor-free", Weight: 0.97},
			{Provider: "opencode", Model: "nemotron-3-ultra-free", Weight: 0.95},
			{Provider: "inferx", Model: "Devstral-2-123B-Instruct-2512-int4-AutoRound", Weight: 0.94},
			{Provider: "groq", Model: "qwen/qwen3.8-27b", Weight: 0.93},
			{Provider: "gmi", Model: "MiniMaxAI/MiniMax-M3", Weight: 0.93},
			{Provider: "groq", Model: "qwen/qwen3.6-27b", Weight: 0.92},
			{Provider: "vercel", Model: "minimax/minimax-m3-free", Weight: 0.92},
			{Provider: "empero", Model: "glm-5.3-flash", Weight: 0.91},
			{Provider: "empero", Model: "deepseek-v4-flash", Weight: 0.91},
			{Provider: "bai", Model: "glm-5.3-flash", Weight: 0.91},
			{Provider: "bai", Model: "qwen3.8-flash", Weight: 0.90},
			{Provider: "inferx", Model: "Qwen3-Coder-Next-FP8", Weight: 0.89},
			{Provider: "zai", Model: "glm-4.7-flash", Weight: 0.89},
			{Provider: "gemini", Model: "gemini-3.6-flash", Weight: 0.89},
			{Provider: "cloudflare", Model: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", Weight: 0.88},
			{Provider: "openrouter", Model: "nvidia/nemotron-3-ultra-550b-a55b:free", Weight: 0.88},
			{Provider: "cloudflare", Model: "@cf/qwen/qwen2.5-coder-32b-instruct", Weight: 0.87},
			{Provider: "orca", Model: "deepseek/deepseek-v4-flash-free", Weight: 0.87},
			{Provider: "openrouter", Model: "z-ai/glm-5.2:free", Weight: 0.86},
			{Provider: "kilo", Model: "nvidia/nemotron-3-ultra-550b-a55b:free", Weight: 0.85},
			{Provider: "gemini", Model: "gemini-3.5-flash", Weight: 0.84},
			{Provider: "inferx", Model: "Qwen3.8-27B-FP8", Weight: 0.84},
			{Provider: "bai", Model: "hy3", Weight: 0.82},
			{Provider: "orca", Model: "qwen/qwen3.8-27b-free", Weight: 0.81},
			{Provider: "ollama", Model: "nemotron-3-ultra", Weight: 0.80},
			{Provider: "groq", Model: "openai/gpt-oss-120b", Weight: 0.78},
			{Provider: "ollama", Model: "gpt-oss:120b", Weight: 0.78},
			{Provider: "gemini", Model: "gemma-4-31b-it", Weight: 0.76},
		},
		SLO: &types.TierSLO{
			MaxLatencyMs: intPtr(60000),
		},
	},
}

func GetTierConfig(tier types.Tier) *types.TierConfig {
	config, ok := tierRegistry[tier]
	if !ok {
		return nil
	}
	return &config
}

func intPtr(i int) *int {
	return &i
}

func GetAllTierConfigs() map[types.Tier]types.TierConfig {
	return tierRegistry
}
