// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces.go -destination=internal/services/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	services "github.com/abdo-355/llm-gateway/internal/services"
	types "github.com/abdo-355/llm-gateway/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockQuotaChecker is a mock of QuotaChecker interface.
type MockQuotaChecker struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaCheckerMockRecorder
	isgomock struct{}
}

// MockQuotaCheckerMockRecorder is the mock recorder for MockQuotaChecker.
type MockQuotaCheckerMockRecorder struct {
	mock *MockQuotaChecker
}

// NewMockQuotaChecker creates a new mock instance.
func NewMockQuotaChecker(ctrl *gomock.Controller) *MockQuotaChecker {
	mock := &MockQuotaChecker{ctrl: ctrl}
	mock.recorder = &MockQuotaCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaChecker) EXPECT() *MockQuotaCheckerMockRecorder {
	return m.recorder
}

// CheckModelQuota mocks base method.
func (m *MockQuotaChecker) CheckModelQuota(ctx context.Context, providerID, model string, limits types.ModelLimits, estimatedTokens int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckModelQuota", ctx, providerID, model, limits, estimatedTokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckModelQuota indicates an expected call of CheckModelQuota.
func (mr *MockQuotaCheckerMockRecorder) CheckModelQuota(ctx, providerID, model, limits, estimatedTokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckModelQuota", reflect.TypeOf((*MockQuotaChecker)(nil).CheckModelQuota), ctx, providerID, model, limits, estimatedTokens)
}

// EstimateTokens mocks base method.
func (m *MockQuotaChecker) EstimateTokens(req types.ChatCompletionRequest) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateTokens", req)
	ret0, _ := ret[0].(int)
	return ret0
}

// EstimateTokens indicates an expected call of EstimateTokens.
func (mr *MockQuotaCheckerMockRecorder) EstimateTokens(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateTokens", reflect.TypeOf((*MockQuotaChecker)(nil).EstimateTokens), req)
}

// HandleProviderRateLimit mocks base method.
func (m *MockQuotaChecker) HandleProviderRateLimit(ctx context.Context, providerID, model string, resp *http.Response) services.RateLimitInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleProviderRateLimit", ctx, providerID, model, resp)
	ret0, _ := ret[0].(services.RateLimitInfo)
	return ret0
}

// HandleProviderRateLimit indicates an expected call of HandleProviderRateLimit.
func (mr *MockQuotaCheckerMockRecorder) HandleProviderRateLimit(ctx, providerID, model, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProviderRateLimit", reflect.TypeOf((*MockQuotaChecker)(nil).HandleProviderRateLimit), ctx, providerID, model, resp)
}

// RecordModelUsage mocks base method.
func (m *MockQuotaChecker) RecordModelUsage(ctx context.Context, providerID, model string, tokensUsed int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordModelUsage", ctx, providerID, model, tokensUsed)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordModelUsage indicates an expected call of RecordModelUsage.
func (mr *MockQuotaCheckerMockRecorder) RecordModelUsage(ctx, providerID, model, tokensUsed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordModelUsage", reflect.TypeOf((*MockQuotaChecker)(nil).RecordModelUsage), ctx, providerID, model, tokensUsed)
}

// MockHealthChecker is a mock of HealthChecker interface.
type MockHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerMockRecorder
	isgomock struct{}
}

// MockHealthCheckerMockRecorder is the mock recorder for MockHealthChecker.
type MockHealthCheckerMockRecorder struct {
	mock *MockHealthChecker
}

// NewMockHealthChecker creates a new mock instance.
func NewMockHealthChecker(ctrl *gomock.Controller) *MockHealthChecker {
	mock := &MockHealthChecker{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthChecker) EXPECT() *MockHealthCheckerMockRecorder {
	return m.recorder
}

// CanExecute mocks base method.
func (m *MockHealthChecker) CanExecute(ctx context.Context, providerID, model string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanExecute", ctx, providerID, model)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanExecute indicates an expected call of CanExecute.
func (mr *MockHealthCheckerMockRecorder) CanExecute(ctx, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanExecute", reflect.TypeOf((*MockHealthChecker)(nil).CanExecute), ctx, providerID, model)
}

// CheckCircuitBreaker mocks base method.
func (m *MockHealthChecker) CheckCircuitBreaker(ctx context.Context, providerID, model string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCircuitBreaker", ctx, providerID, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckCircuitBreaker indicates an expected call of CheckCircuitBreaker.
func (mr *MockHealthCheckerMockRecorder) CheckCircuitBreaker(ctx, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCircuitBreaker", reflect.TypeOf((*MockHealthChecker)(nil).CheckCircuitBreaker), ctx, providerID, model)
}

// GetAllHealthMetrics mocks base method.
func (m *MockHealthChecker) GetAllHealthMetrics(ctx context.Context) []services.HealthMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHealthMetrics", ctx)
	ret0, _ := ret[0].([]services.HealthMetrics)
	return ret0
}

// GetAllHealthMetrics indicates an expected call of GetAllHealthMetrics.
func (mr *MockHealthCheckerMockRecorder) GetAllHealthMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHealthMetrics", reflect.TypeOf((*MockHealthChecker)(nil).GetAllHealthMetrics), ctx)
}

// GetCircuitState mocks base method.
func (m *MockHealthChecker) GetCircuitState(ctx context.Context, providerID, model string) services.CircuitState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCircuitState", ctx, providerID, model)
	ret0, _ := ret[0].(services.CircuitState)
	return ret0
}

// GetCircuitState indicates an expected call of GetCircuitState.
func (mr *MockHealthCheckerMockRecorder) GetCircuitState(ctx, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCircuitState", reflect.TypeOf((*MockHealthChecker)(nil).GetCircuitState), ctx, providerID, model)
}

// GetHealthMetrics mocks base method.
func (m *MockHealthChecker) GetHealthMetrics(ctx context.Context, providerID, model string) services.HealthMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthMetrics", ctx, providerID, model)
	ret0, _ := ret[0].(services.HealthMetrics)
	return ret0
}

// GetHealthMetrics indicates an expected call of GetHealthMetrics.
func (mr *MockHealthCheckerMockRecorder) GetHealthMetrics(ctx, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthMetrics", reflect.TypeOf((*MockHealthChecker)(nil).GetHealthMetrics), ctx, providerID, model)
}

// RecordFailure mocks base method.
func (m *MockHealthChecker) RecordFailure(ctx context.Context, providerID, model string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordFailure", ctx, providerID, model)
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockHealthCheckerMockRecorder) RecordFailure(ctx, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockHealthChecker)(nil).RecordFailure), ctx, providerID, model)
}

// RecordSuccess mocks base method.
func (m *MockHealthChecker) RecordSuccess(ctx context.Context, providerID, model string, latencyMs int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSuccess", ctx, providerID, model, latencyMs)
}

// RecordSuccess indicates an expected call of RecordSuccess.
func (mr *MockHealthCheckerMockRecorder) RecordSuccess(ctx, providerID, model, latencyMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSuccess", reflect.TypeOf((*MockHealthChecker)(nil).RecordSuccess), ctx, providerID, model, latencyMs)
}

// MockProviderCaller is a mock of ProviderCaller interface.
type MockProviderCaller struct {
	ctrl     *gomock.Controller
	recorder *MockProviderCallerMockRecorder
	isgomock struct{}
}

// MockProviderCallerMockRecorder is the mock recorder for MockProviderCaller.
type MockProviderCallerMockRecorder struct {
	mock *MockProviderCaller
}

// NewMockProviderCaller creates a new mock instance.
func NewMockProviderCaller(ctrl *gomock.Controller) *MockProviderCaller {
	mock := &MockProviderCaller{ctrl: ctrl}
	mock.recorder = &MockProviderCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderCaller) EXPECT() *MockProviderCallerMockRecorder {
	return m.recorder
}

// CallProvider mocks base method.
func (m *MockProviderCaller) CallProvider(baseURL, apiKey, model string, request types.ChatCompletionRequest, timeoutMs int, ctx context.Context, providerType string, auth types.ProviderAuth) (*types.ChatCompletionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallProvider", baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth)
	ret0, _ := ret[0].(*types.ChatCompletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallProvider indicates an expected call of CallProvider.
func (mr *MockProviderCallerMockRecorder) CallProvider(baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallProvider", reflect.TypeOf((*MockProviderCaller)(nil).CallProvider), baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth)
}

// StreamProviderChannel mocks base method.
func (m *MockProviderCaller) StreamProviderChannel(baseURL, apiKey, model string, request types.ChatCompletionRequest, timeoutMs int, ctx context.Context, providerType string, auth types.ProviderAuth) types.StreamResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamProviderChannel", baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth)
	ret0, _ := ret[0].(types.StreamResult)
	return ret0
}

// StreamProviderChannel indicates an expected call of StreamProviderChannel.
func (mr *MockProviderCallerMockRecorder) StreamProviderChannel(baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamProviderChannel", reflect.TypeOf((*MockProviderCaller)(nil).StreamProviderChannel), baseURL, apiKey, model, request, timeoutMs, ctx, providerType, auth)
}
