name: Deploy to Coolify

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Trigger Coolify deploy
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
